
services:
  test-task-app:
    build: ./
    command: ["./wait-for-postgres.sh", "./test-task-app"]

    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
    - .env  

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: bookTest_db   
    ports:
      - "5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data